#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 08 17:00:33 CET 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto af633894d4814a8d85b5bc8948905381 --incr --debug typical --relax --mt 8 -L grlib -L techmap -L gaisler -L work -L eth -L opencores -L esa -L secureip -L xpm --snapshot testbench_behav work.testbench -log elaborate.log"
xelab -wto af633894d4814a8d85b5bc8948905381 --incr --debug typical --relax --mt 8 -L grlib -L techmap -L gaisler -L work -L eth -L opencores -L esa -L secureip -L xpm --snapshot testbench_behav work.testbench -log elaborate.log

